// Public surface of the generated REST client (D-09-1). Import models + the
// client factory from here; the generated `schema.ts` is regenerated by
// `scripts/gen-api.sh` (committed, not runtime-generated).
import type { components } from "./schema";

export type { ApiErrorBody, RateLimit, TokenGetter } from "./client";
export { ApiError, createApiClient, readRateLimit, unwrap } from "./client";
export type { components, paths } from "./schema";

type Schemas = components["schemas"];

// Responses
export type PersonaSummary = Schemas["PersonaSummary"];
export type PersonaDetail = Schemas["PersonaDetail"];
export type ConversationSummary = Schemas["ConversationSummary"];
export type ConversationDetail = Schemas["ConversationDetail"];
export type MessageView = Schemas["MessageView"];
export type RunStatusResponse = Schemas["RunStatusResponse"];
export type ToolSummary = Schemas["ToolSummary"];
export type CreditsResponse = Schemas["CreditsResponse"];
export type UsageEntry = Schemas["UsageEntry"];
export type AuthoringDraft = Schemas["AuthoringDraft"];
export type ClarifyingQuestion = Schemas["ClarifyingQuestion"];

// Requests
export type CreatePersonaRequest = Schemas["CreatePersonaRequest"];
export type UpdatePersonaRequest = Schemas["UpdatePersonaRequest"];
export type AuthorPersonaRequest = Schemas["AuthorPersonaRequest"];
export type CreateConversationRequest = Schemas["CreateConversationRequest"];
export type PostMessageRequest = Schemas["PostMessageRequest"];
export type ChannelContext = Schemas["ChannelContext"];
export type StartRunRequest = Schemas["StartRunRequest"];
export type RespondToRunRequest = Schemas["RespondToRunRequest"];

// Spec K5 — Memory (the interactive knowledge-graph)
export type MemoryWindowResponse = Schemas["MemoryWindowResponse"];
export type MemoryNodeSummary = Schemas["MemoryNodeSummary"];
export type MemoryLinkEdge = Schemas["MemoryLinkEdge"];
export type MemoryNodeDetail = Schemas["MemoryNodeDetail"];
export type MemoryLinkView = Schemas["MemoryLinkView"];
export type MemoryEvolutionEntry = Schemas["MemoryEvolutionEntry"];
export type MemorySearchResponse = Schemas["MemorySearchResponse"];
export type MemorySearchResult = Schemas["MemorySearchResult"];
export type MemoryCorrectionRequest = Schemas["MemoryCorrectionRequest"];

// Spec K11 (D-K11-5) — the episodic browser, a standalone graph separate from
// the K5 concept graph: gist cluster-nodes, drillable to raw member leaves.
export type EpisodicWindowResponse = Schemas["EpisodicWindowResponse"];
export type EpisodicGistView = Schemas["EpisodicGistView"];
export type EpisodicMemberView = Schemas["EpisodicMemberView"];
export type EpisodicMembersResponse = Schemas["EpisodicMembersResponse"];

// Spec K11 (D-K11-1 / D-K11-2) — the cross-layer forget confirm: a concept-node
// delete previews the episodic evidence it would also erase, persona-labelled
// and deselectable, before anything is committed.
export type ForgetCandidate = Schemas["ForgetCandidate"];
export type ForgetEpisodicRef = Schemas["ForgetEpisodicRef"];
export type ForgetPreviewResponse = Schemas["ForgetPreviewResponse"];
export type ForgetRequest = Schemas["ForgetRequest"];
